language: ruby
rvm:
  - 2.7.1
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rails db:create db:migrate --trace
services:
  - redis-server
notifications:
  email:
    recipients:
      - abouelnourmohamed5@gmail.com
    on_success: change
    on_failure: change
before_install:
  - rvm get stable
  - gem update --system
  - gem install bundler
