require("@rails/ujs").start()
//require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require('admin/jquery')
require('admin/bootstrap')
require('admin/bootstrap-datepicker')
require('admin/bootstrap-multiselect')
require('admin/jquery.placeholder')
require('admin/jquery.browser.mobile')
require('admin/magnific-popup')
require('admin/nanoscroller')
require('admin/bootstrap-tagsinput')

require('admin/theme')
require('admin/sidebar')
require('admin/add_book')
