// libraries
require("@rails/ujs").start()
require("@rails/activestorage").start()
require("channels")
require('jquery')
require('popper.js')
require('bootstrap')
require('bootstrap-datepicker')
require('placeholder')
require('magnific-popup')
require('datatables.net-bs')
require('bootstrap-tagsinput')
// files
//require('admin/theme')
require('admin/sidebar')
require('admin/add_book')
require('admin/datatable_book')
