require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require('template/jquery.min')
require('template/bootstrap.min')
require('template/owl.carousel.min')
require('template/megamenu')